### ISSUE TITLE
InvalidRootHashException on #4133443

### ISSUE THREAD

**Issue by longfin** [planetarium/lib9c#1237]
Some nodes seem to fail adding block([#4133443](https://9cscan.com/blocks/4133443)) on v100260.

**Comment by longfin** [comment]
@area363 Could you leave the detailed information about it?

**Comment by area363** [comment]
```
Libplanet.Blocks.InvalidBlockStateRootHashException:
Block #4133443 ad46eee6d2636bb0ed6cb7ff6531bd48ea539d23075c9a36bbd521dd77dca155's state root hash is e708d7b8fe500775fb6cf99a7ffe85a878c0aa74ef14a9e33e5682146025ef7d, but the execution result is 3a69a2decdc0f82ca0d0c77d3d059652abffab63e1dda55f42abe55272cd7c1e.
at Libplanet.Blockchain.BlockChain`1.ExecuteActions(Block`1 block, Nullable`1 stateCompleters) in /app/NineChronicles.Headless/Lib9c/.Libplanet/Libplanet/Blockchain/BlockChain.cs:line 840
at Libplanet.Blockchain.BlockChain`1.Append(Block`1 block, Boolean evaluateActions, Boolean renderBlocks, Boolean renderActions, IReadOnlyList`1 actionEvaluations, Nullable`1 stateCompleters) in /app/NineChronicles.Headless/Lib9c/.Libplanet/Libplanet/Blockchain/BlockChain.cs:line 926
at Libplanet.Net.Swarm`1.AppendPreviousBlocks(BlockChain`1 blockChain, SortedList`2 candidate, Boolean evaluateActions) in /app/NineChronicles.Headless/Lib9c/.Libplanet/Libplanet.Net/Swarm.BlockCandidate.cs:line 180
at Libplanet.Net.Swarm`1.BlockCandidateProcess(SortedList`2 candidate, CancellationToken cancellationToken) in /app/NineChronicles.Headless/Lib9c/.Libplanet/Libplanet.Net/Swarm.BlockCandidate.cs:line 113
```

**Comment by area363** [comment]
![Image](https://user-images.githubusercontent.com/42176649/182280504-f62f4164-b1c2-4e34-96aa-3955a789b844.png)

It appears that the `RapidCombination6`(https://9cscan.com/tx/add4c0cfa723d56a8cb01a685c8387b085f9fdad06560adeeac57d9d37025094) action in `#4133443` doesn't have a mail associated with the action.

This issue is similar to the currently open fix PR(https://github.com/planetarium/lib9c/pull/1212) so I'll add this block in the fix condition range (https://github.com/planetarium/lib9c/pull/1212/files#diff-e28348a9e18530ee05d841f42aee46bfe95c29bd82fff2622548702bccae22e4R130-R153). cc @planetarium/9c-dev

**Comment by area363** [comment]
I'm going to append blocks from `#4133443` to `#4372673` to see if there are other `RB6` errors and update the PR after.
