### ISSUE TITLE
`InvalidCastException` while executing `CreateCustomActions` for the `op_validator_set` action in version `v200010`

### ISSUE THREAD

**Issue by area363** [planetarium/lib9c#1890]
- Block: https://9cscan.com/blocks/6398201
- Transaction: https://9cscan.com/tx/5d122993dd68bcd264da1651c921141ca892931124f190ee03460f01f32c5833
- Error stack trace when executing block `#6398201` with [v200010](https://github.com/planetarium/lib9c/tree/v200010):
```
System.InvalidCastException: Unable to cast object of type 'Bencodex.Types.Binary' to type 'Bencodex.Types.Integer'.
   at Bencodex.Types.Dictionary.GetValue[T](Byte[] name)
   at Libplanet.Consensus.Validator..ctor(Dictionary bencoded) in C:\Users\kidon\Desktop\NineChronicles.DataProvider\NineChronicles.Headless\Lib9c\.Libplanet\Libplanet\Consensus\Validator.cs:line 55
   at Libplanet.Consensus.Validator..ctor(IValue bencoded) in C:\Users\kidon\Desktop\NineChronicles.DataProvider\NineChronicles.Headless\Lib9c\.Libplanet\Libplanet\Consensus\Validator.cs:line 45
   at Nekoyume.Action.ValidatorSetOperate.LoadPlainValue(IValue plainValue) in C:\Users\kidon\Desktop\NineChronicles.DataProvider\NineChronicles.Headless\Lib9c\Lib9c\Action\ValidatorSetOperate.cs:line 146
   at Libplanet.Action.PolymorphicAction`1.LoadPlainValue(Dictionary plainValue) in C:\Users\kidon\Desktop\NineChronicles.DataProvider\NineChronicles.Headless\Lib9c\.Libplanet\Libplanet\Action\PolymorphicAction.cs:line 248
   at Libplanet.Action.PolymorphicAction`1.LoadPlainValue(IValue plainValue) in C:\Users\kidon\Desktop\NineChronicles.DataProvider\NineChronicles.Headless\Lib9c\.Libplanet\Libplanet\Action\PolymorphicAction.cs:line 255
   at Libplanet.Action.ActionEvaluator.CreateCustomActions(IActionTypeLoaderContext actionTypeLoaderContext, ITransaction tx)+MoveNext() in C:\Users\kidon\Desktop\NineChronicles.DataProvider\NineChronicles.Headless\Lib9c\.Libplanet\Libplanet\Action\ActionEvaluator.cs:line 839
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
   at System.Collections.Immutable.ImmutableList`1.CreateRange(IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableList`1.AddRange(IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableList.CreateRange[T](IEnumerable`1 items)
   at Libplanet.Action.ActionEvaluator.EvaluateTx(IPreEvaluationBlockHeader blockHeader, ITransaction tx, IAccountStateDelta previousStates, Boolean rehearsal, ITrie previousBlockStatesTrie) in C:\Users\kidon\Desktop\NineChronicles.DataProvider\NineChronicles.Headless\Lib9c\.Libplanet\Libplanet\Action\ActionEvaluator.cs:line 623
   at Libplanet.Action.ActionEvaluator.EvaluateBlock(IPreEvaluationBlock block, IAccountStateDelta previousStates, ITrie previousBlockStatesTrie)+MoveNext() in C:\Users\kidon\Desktop\NineChronicles.DataProvider\NineChronicles.Headless\Lib9c\.Libplanet\Libplanet\Action\ActionEvaluator.cs:line 578
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
   at System.Collections.Immutable.ImmutableList`1.CreateRange(IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableList`1.AddRange(IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableList.ToImmutableList[TSource](IEnumerable`1 source)
   at Libplanet.Action.ActionEvaluator.Evaluate(IPreEvaluationBlock block) in C:\Users\kidon\Desktop\NineChronicles.DataProvider\NineChronicles.Headless\Lib9c\.Libplanet\Libplanet\Action\ActionEvaluator.cs:line 132
   at Libplanet.Blockchain.BlockChain`1.ExecuteActions(Block`1 block) in C:\Users\kidon\Desktop\NineChronicles.DataProvider\NineChronicles.Headless\Lib9c\.Libplanet\Libplanet\Blockchain\BlockChain.cs:line 935
```
- Full state tx status:
![Image](https://user-images.githubusercontent.com/42176649/236747740-9c5d2d51-fb5f-4b3b-b285-8ed3ef143cf9.png)

**Comment by area363** [comment]
Issue obsolete.
