### ISSUE TITLE
Failed update-submodule

### ISSUE THREAD

**Issue by ipdae** [planetarium/lib9c#925]
```It updates the submodule referring to [*{submodule_repository.name}*]({submodule_repository.html_url}) to {submodule_ref_type} *{submodule_ref_name}* ({submodule_repository.full_name}@{submodule_commit.sha}).
' 'planetarium/NineChronicles:rc-v100[170](https://github.com/planetarium/lib9c/runs/5882304124?check_suite_focus=true#step:2:170)?' 'planetarium/NineChronicles.Headless:rc-v100170?'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/_actions/planetarium/submodule-updater/main/sur/__main__.py", line 30, in <module>
    main()
  File "/home/runner/work/_actions/planetarium/submodule-updater/main/sur/__main__.py", line 21, in main
Notice: Configuration: Config(github=<GitHub [token ghp_...]>, source_repository=<Repository [planetarium/lib9c]>, ref=<Reference [refs/heads/rc-v100170]>, targets={<Repository [planetarium/NineChronicles]>: <Repository Branch [rc-v100170]>, <Repository [planetarium/NineChronicles.Headless]>: <Repository Branch [rc-v100170]>}, committer=pygit2.Signature('Submodule Updater', 'engineering+submodule-updater@planetariumhq.com', 1649407843, 0, 'utf-8'), dry_run=False, pr_title_format='Update {submodule_repository.name} to {submodule_ref_name}', pr_description_format='*This pull request was automatically generated by Submodule Updater.*\n\nIt updates the submodule referring to [*{submodule_repository.name}*]({submodule_repository.html_url}) to {submodule_ref_type} *{submodule_ref_name}* ({submodule_repository.full_name}@{submodule_commit.sha}).\n')
Notice: Updating planetarium/NineChronicles:rc-v100170...
Notice: Cloning planetarium/NineChronicles:rc-v100170 to /tmp/tmpothehorx...
Notice: Cloned planetarium/NineChronicles:rc-v100170 to /tmp/tmpothehorx
Notice: Initializing submodule nekoyume/Assets/_Scripts/Lib9c/lib9c...
Notice: Initializing submodule .Libplanet...
Notice: Submodules in planetarium/NineChronicles:rc-v100170 are up to date.
Notice: Updating planetarium/NineChronicles.Headless:rc-v100170...
Notice: Cloning planetarium/NineChronicles.Headless:rc-v100170 to /tmp/tmpr0gjh4as...
Notice: Cloned planetarium/NineChronicles.Headless:rc-v100170 to /tmp/tmpr0gjh4as
Notice: Initializing submodule Lib9c...
Notice: Initializing submodule .Libplanet...
Error: Unhandled exception occurred: Failed to push refs/heads/submodule-update/lib9c/rc-v100170--bebb3b4 to ***github.com/planet-submodule-updater/NineChronicles.Headless.git; the last 3 lines of the log are (the complete log file: /tmp/submodule-updater-y_pfoagj.log):
  To https://github.com/planet-submodule-updater/NineChronicles.Headless.git
   ! [remote rejected] submodule-update/lib9c/rc-v100170--bebb3b4 -> submodule-update/lib9c/rc-v100170--bebb3b4 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/push_docker_image.yml` without `workflow` scope)
  error: failed to push some refs to 'https://github.com/planet-submodule-updater/NineChronicles.Headless.git'

    cli.main()
  File "/home/runner/work/_actions/planetarium/submodule-updater/main/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/_actions/planetarium/submodule-updater/main/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/work/_actions/planetarium/submodule-updater/main/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/_actions/planetarium/submodule-updater/main/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/work/_actions/planetarium/submodule-updater/main/sur/cli.py", line [209](https://github.com/planetarium/lib9c/runs/5882304124?check_suite_focus=true#step:2:209), in cli
    run(config)
  File "/home/runner/work/_actions/planetarium/submodule-updater/main/sur/update.py", line 32, in run
    update_target_repo(config, target_repo, target_branch)
  File "/home/runner/work/_actions/planetarium/submodule-updater/main/sur/update.py", line 107, in update_target_repo
    pr = open_pull_request(
  File "/home/runner/work/_actions/planetarium/submodule-updater/main/sur/update.py", line 280, in open_pull_request
    push(cloned_repository, remote, f"refs/heads/{temp_branch_name}")
  File "/home/runner/work/_actions/planetarium/submodule-updater/main/sur/update.py", line 401, in push
    raise GitError(
_pygit2.GitError: Failed to push refs/heads/submodule-update/lib9c/rc-v100170--bebb3b4 to ***github.com/planet-submodule-updater/NineChronicles.Headless.git; the last 3 lines of the log are (the complete log file: /tmp/submodule-updater-y_pfoagj.log):
  To https://github.com/planet-submodule-updater/NineChronicles.Headless.git
   ! [remote rejected] submodule-update/lib9c/rc-v100170--bebb3b4 -> submodule-update/lib9c/rc-v100170--bebb3b4 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/push_docker_image.yml` without `workflow` scope)
  error: failed to push some refs to 'https://github.com/planet-submodule-updater/NineChronicles.Headless.git'``

**Comment by dahlia** [comment]
It's probably due to @planet-submodule-updater hadn't had rights to maintain the _NineChronicles.Headless_ repository.  I give it the appropriate rights.  I guess it would work well now; I'm going to close when I see if it's really fixed.
